[package]
name = "encryptor_tui"
version = "0.1.0"
authors = ["JayanAXHF <sunil.chdry@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
tui-textarea = "0.7.0"
tui-input = "0.11.1"
