[package]
name = "vigenere_cipher"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "0.12.12", features=["blocking", "json"]}
serde_json = "1.0.135"
utils = {path = "../utils/"}
